# WINDOWS ONLY. Registers 3 Task Scheduler tasks with autorestart on failure + on-boot trigger.
# User decision: Task Scheduler, no systemd. Wrappers kill the child in 10-20 min, so
# tasks restart on failure (RestartOnFailure, 1-min interval, 999 attempts) to self-heal.
#
# Start order after reboot: sing-box -> relay -> gateway (depends on the previous layer).
# Enforced via staggered boot delays (1/2/3 min) + relay/gateway restart if their
# dependency port is not yet listening.
#
# Secrets: none in this file. sing-box config path and tokens come from env/files only.
# Usage (elevated PowerShell):
#   .\install-scheduler.ps1 [-SingBoxBin sing-box] [-SingBoxConfig <path>] [-Unregister]
param(
  [string]$SingBoxBin = 'sing-box',
  [string]$SingBoxConfig = '',
  [switch]$Unregister
)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
if (-not $SingBoxConfig) {
  $gen = Join-Path $Root 'sing-box/config.json'
  $example = Join-Path $Root 'sing-box/config.example.json'
  $SingBoxConfig = if (Test-Path $gen) { $gen } else { $example }
}
$Tasks = @(
  @{ Name = 'oc-singbox'; Delay = 'PT1M';  Cmd = "$SingBoxBin run -c `"$SingBoxConfig`"" },
  @{ Name = 'oc-relay';   Delay = 'PT2M';  Cmd = "node `"$Root\src\relay\rr-socks.mjs`"" },
  @{ Name = 'oc-gateway'; Delay = 'PT3M';  Cmd = "bun run `"$Root\src\index.ts`"" }
)

if ($Unregister) {
  foreach ($t in $Tasks) {
    schtasks /Delete /TN $t.Name /F 2>$null
    Write-Host "removed $($t.Name)"
  }
  exit 0
}

foreach ($t in $Tasks) {
  # Per-task wrapper: runs the command, restarts it on exit (autorestart), run from repo root.
  $wrapper = Join-Path $PSScriptRoot "$($t.Name)-run.ps1"
  Set-Content -Path $wrapper -Encoding UTF8 -Value @(
    '# generated by install-scheduler.ps1 - hands off'
    "`$ErrorActionPreference = 'Continue'"
    "Set-Location `"$Root`""
    'while ($true) {'
    "  Write-Host `"[$(($t.Name))] start: $($t.Cmd)`""
    "  cmd /c `"$($t.Cmd) 2>&1`""
    "  Write-Host `"[$(($t.Name))] exited $LASTEXITCODE - restart in 60s`""
    '  Start-Sleep -Seconds 60'
    '}'
  )
  # /RU SYSTEM runs at boot without a logged-on user; /RL HIGHEST for bind + process control.
  # /SC ONSTART = on-boot trigger with staggered delay; /F overwrites on re-install.
  schtasks /Create /TN $t.Name /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$wrapper`"" `
    /SC ONSTART /DELAY $t.Delay /RU SYSTEM /RL HIGHEST /F | Out-Null
  # Restart-on-failure hardening: up to 999 restarts, 1-min gap, and restart if the
  # task itself fails to start (covers the wrapper-kills-child 10-20min quirk).
  $xml = schtasks /Query /TN $t.Name /XML
  $xml = $xml -replace '<RestartOnFailure>.*?</RestartOnFailure>',
    '<RestartOnFailure><Interval>PT1M</Interval><Count>999</Count></RestartOnFailure>'
  $tmp = [System.IO.Path]::GetTempFileName()
  Set-Content -Path $tmp -Encoding UTF8 -Value $xml
  schtasks /Create /TN $t.Name /XML $tmp /F | Out-Null
  Remove-Item $tmp -Force
  schtasks /Run /TN $t.Name 2>$null | Out-Null
  Write-Host "registered+started $($t.Name) (boot delay $($t.Delay)): $($t.Cmd)"
}
Write-Host 'Start order: oc-singbox -> oc-relay -> oc-gateway (staggered PT1M/PT2M/PT3M boot delays).'
Write-Host 'Verify: .\scripts\verify-health.ps1; .\scripts\verify-relay.ps1'
