# WINDOWS ONLY. Registers 4 Task Scheduler tasks with autorestart on failure + on-boot trigger.
# User decision: Task Scheduler, no systemd. Wrappers kill the child in 10-20 min, so
# tasks restart on failure (RestartOnFailure, 1-min interval, 999 attempts) to self-heal.
#
# Start order after reboot: sing-box -> relay -> gateway (depends on the previous layer).
# Enforced via staggered boot delays (1/2/3 min) + relay/gateway restart if their
# dependency port is not yet listening. The watchdog (oc-watchdog, 4th task) closes the
# v1 supervision loop: crash -> toast + heal via `zen status --self-heal` every 5 min.
#
# Compat: reinstalling over the old 3-task layout only ADDS oc-watchdog; the other
# three are overwritten in place (/F). Uninstall (-Unregister) removes all 4.
# Live registration needs elevation; pass -WhatIf for a no-mutation dry run.
#
# Secrets: none in this file. sing-box config path and tokens come from env/files only.
# Usage (elevated PowerShell):
#   .\install-scheduler.ps1 [-SingBoxBin sing-box] [-SingBoxConfig <path>] [-Unregister] [-WhatIf]
param(
  [string]$SingBoxBin = 'sing-box',
  [string]$SingBoxConfig = '',
  [switch]$Unregister,
  [switch]$WhatIf
)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
if (-not $SingBoxConfig) {
  $gen = Join-Path $Root 'sing-box/config.json'
  $example = Join-Path $Root 'sing-box/config.example.json'
  $SingBoxConfig = if (Test-Path $gen) { $gen } else { $example }
}
# Same zen entry resolution as the gateway task (`bun run <entry>`): prefer the
# compiled dist output when `bun run build` has been run, else the dev entry.
# Never a hardcoded dev path: both candidates derive from $Root.
$ZenEntry = Join-Path $Root 'src\index.ts'
$ZenDist = Join-Path $Root 'dist\index.js'
if (Test-Path $ZenDist) { $ZenEntry = $ZenDist }
$Tasks = @(
  @{ Name = 'oc-singbox';  Delay = 'PT1M';  Cmd = "$SingBoxBin run -c `"$SingBoxConfig`"" },
  @{ Name = 'oc-relay';    Delay = 'PT2M';  Cmd = "node `"$Root\src\relay\rr-socks.mjs`"" },
  @{ Name = 'oc-gateway';  Delay = 'PT3M';  Cmd = "bun run `"$Root\src\index.ts`"" },
  @{ Name = 'oc-watchdog'; Delay = 'PT5M';  Cmd = "bun run `"$ZenEntry`" status --self-heal"; Once = $true; Repeat = 'PT5M' }
)

function Invoke-Plan {
  param([string]$Step, [scriptblock]$Action)
  if ($WhatIf) { Write-Host "WhatIf: $Step" } else { & $Action }
}

if ($Unregister) {
  foreach ($t in $Tasks) {
    Invoke-Plan "schtasks /Delete /TN $($t.Name) /F" { schtasks /Delete /TN $t.Name /F 2>$null }
    Write-Host "removed $($t.Name)"
  }
  exit 0
}

foreach ($t in $Tasks) {
  # Per-task wrapper: long-running services loop forever (autorestart); the
  # watchdog is single-shot (exit code = self-heal exit 0/1/2) and the
  # PT5M schedule repetition below drives the 5-min cadence.
  $wrapper = Join-Path $PSScriptRoot "$($t.Name)-run.ps1"
  if ($t.Once) {
    $body = @(
      '# generated by install-scheduler.ps1 - hands off'
      "`$ErrorActionPreference = 'Continue'"
      "Set-Location `"$Root`""
      "cmd /c `"$($t.Cmd) 2>&1`""
      'exit $LASTEXITCODE'
    )
  } else {
    $body = @(
      '# generated by install-scheduler.ps1 - hands off'
      "`$ErrorActionPreference = 'Continue'"
      "Set-Location `"$Root`""
      'while ($true) {'
      "  Write-Host `"[$(($t.Name))] start: $($t.Cmd)`""
      "  cmd /c `"$($t.Cmd) 2>&1`""
      "  Write-Host `"[$(($t.Name))] exited $LASTEXITCODE - restart in 60s`""
      '  Start-Sleep -Seconds 60'
      '}'
    )
  }
  Invoke-Plan "write $wrapper" { Set-Content -Path $wrapper -Encoding UTF8 -Value $body }
  # /RU SYSTEM runs at boot without a logged-on user; /RL HIGHEST for bind + process control.
  # /SC ONSTART = on-boot trigger with staggered delay; /F overwrites on re-install.
  Invoke-Plan "schtasks /Create /TN $($t.Name) /SC ONSTART /DELAY $($t.Delay) /TR $wrapper" {
    schtasks /Create /TN $t.Name /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$wrapper`"" `
      /SC ONSTART /DELAY $t.Delay /RU SYSTEM /RL HIGHEST /F | Out-Null
  }
  # Restart-on-failure hardening: up to 999 restarts, 1-min gap, and restart if the
  # task itself fails to start (covers the wrapper-kills-child 10-20min quirk).
  # Watchdog additionally repeats its boot trigger every PT5M (Duration omitted =
  # indefinite) so `status --self-heal` runs on a 5-min cadence, not just at boot.
  Invoke-Plan "patch XML for $($t.Name) (RestartOnFailure$(if ($t.Repeat) { '; Repetition ' + $t.Repeat }))" {
    $xml = schtasks /Query /TN $t.Name /XML
    $xml = $xml -replace '<RestartOnFailure>.*?</RestartOnFailure>',
      '<RestartOnFailure><Interval>PT1M</Interval><Count>999</Count></RestartOnFailure>'
    if ($t.Repeat) {
      $xml = $xml -replace '</BootTrigger>',
        "<Repetition><Interval>$($t.Repeat)</Interval><StopAtDurationEnd>false</StopAtDurationEnd></Repetition></BootTrigger>"
    }
    $tmp = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $tmp -Encoding UTF8 -Value $xml
    schtasks /Create /TN $t.Name /XML $tmp /F | Out-Null
    Remove-Item $tmp -Force
  }
  Invoke-Plan "schtasks /Run /TN $($t.Name)" { schtasks /Run /TN $t.Name 2>$null | Out-Null }
  Write-Host "registered+started $($t.Name) (boot delay $($t.Delay)): $($t.Cmd)"
}
Write-Host 'Start order: oc-singbox -> oc-relay -> oc-gateway (staggered PT1M/PT2M/PT3M boot delays).'
Write-Host 'Watchdog: oc-watchdog runs `zen status --self-heal` every PT5M (boot delay PT5M + trigger repetition).'
Write-Host 'Verify: .\scripts\verify-health.ps1; .\scripts\verify-relay.ps1'
